version: '3.8'

services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo_data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=hackathon_secure_123
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=hackathon_secure_123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
