[options]
; Database operations password
admin_passwd = hackathon_admin
; Use the current Linux user for database connection
db_host = False
db_port = False
db_user = False
db_password = False
; Expose the JSON-RPC API on port 8069
xmlrpc_port = 8069
; Define where custom modules will go if needed
addons_path = odoo_framework/addons